### ISSUE TITLE
Specify crystal version

### ISSUE THREAD

**Issue by hanneskaeufler** [hanneskaeufler/blog#68]
It assumes newest version which ... nope.

Must resolve https://circleci.com/gh/hanneskaeufler/blog/288

**Comment by paulcsmith** [comment]
Just  FYI, newer projects are generated with this so Heroku doesn't break https://github.com/luckyframework/lucky_cli/blob/master/src/web_app_skeleton/.crystal-version

**Comment by hanneskaeufler** [comment]
Closed with ea432d2f33c7a86c20cd40a75abb68067af10c00
